<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 2017/11/8
 * Time: 18:44
 */

namespace app\models;


use yii\base\Model;

class WaresSearchForm extends Model
{
    public $keyword;
    public $minPrice;
    public $maxPrice;
    public function rules()
    {
        return [
            [['minPrice','maxPrice'],'number'],
            ['keyword','safe']
        ]; // TODO: Change the autogenerated stub
    }

}